import Pic from '@/components/Pic';import Link from 'next/link';import {site as art} from '@/lib/photos';import {testimonials} from '@/lib/data';
export const metadata={title:'About',description:'The studio behind Aurelia Estates: philosophy, architecture, craft and process.',alternates:{canonical:'/about'}};
const S=[['Our philosophy','We represent houses the way an architect would draw them: light first, structure second, furniture last.','exterior'],['Architecture','Every residence in the collection is chosen for spatial clarity, honest material and a considered relationship to landscape.','living'],['Design approach','We read plans and sections before photographs, and visit at three times of day.','kitchen'],['Craftsmanship','Stone cut by hand, oak joined without fasteners, steel finished by the same workshop for a decade.','bath']] as const;
export default function A(){return <div className="about"><header className="phero"><Pic src={art(99,'exterior')} alt="Studio project at dusk" priority sizes="100vw"/><div><h1>Architecture, represented.</h1><p>An advisory studio for extraordinary houses.</p></div></header>
 {S.map(([t,d,k],i)=><section key={t} className={'sec split '+(i%2?'rev':'')}><div><h2>{t}</h2><p className="lead">{d}</p></div><Pic src={art(100+i,k)} alt={t} cls="tall"/></section>)}
 <section className="sec"><h2>Our process</h2><ol className="steps"><li>Brief: your life, in plain language.</li><li>Curate: three residences, no more.</li><li>Walk: private viewings with the architect’s drawings.</li><li>Close: negotiation and stewardship.</li></ol></section>
 <section className="sec"><h2>The team</h2><ul className="grid3">{['Elena Marsh','Tomás Vidal','Ingrid Lund'].map((n,i)=><li key={n}><Pic src={art(120+i,'portrait')} alt={`Portrait of ${n}`} cls="portrait"/><h3>{n}</h3><p>{['Principal','Head of Architecture','Client Director'][i]}</p></li>)}</ul></section>
 <section className="sec"><h2>Recognition</h2><ul className="tags"><li>Luxury Property Awards, Agency of the Year</li><li>Architectural Digest Real Estate Honoree</li><li>International Property Awards, Design</li></ul></section>
 <section className="sec"><h2>Client words</h2>{testimonials.map(t=><figure key={t.name} className="q2"><blockquote>“{t.text}”</blockquote><figcaption>★★★★★ {t.name}, {t.role}</figcaption></figure>)}</section>
 <section className="cta"><Pic src={art(140,'garden')} alt="Garden at golden hour" sizes="100vw"/><div><h2>Begin with a conversation.</h2><Link className="pill" href="/contact">Request a private consultation</Link></div></section></div>}
