import Link from 'next/link';import Pic from './Pic';import {site as art} from '@/lib/photos';import {properties,testimonials,usd} from '@/lib/data';
const H=({t,s}:{t:string;s?:string})=><div className="sh"><h2>{t}</h2>{s&&<p>{s}</p>}</div>;
const amen=['Infinity pool','Spa','Cinema','Gym','Smart home','Private garden','Outdoor kitchen','Garage'];
const det=[['Materials','exterior',3],['Windows','living',5],['Stone','kitchen',8],['Timber','bedroom',11],['Lighting','bath',13],['Craft','terrace',17]] as const;
export default function Sections(){return <>
<section id="intro" className="sec split"><div><H t="A house composed like a sequence of rooms." s="Aurelia Estate sits on a private ridge above Los Angeles: 6,800 square feet across four bedrooms, five bathrooms and three terraces, every room framed by the canyon."/><p className="price">$8,400,000</p></div><Pic src={art(7,'exterior')} alt="Aurelia Estate exterior" sizes="50vw" cls="tall"/></section>
<section className="sec split rev"><Pic src={art(21,'exterior')} alt="Cantilevered architecture" cls="tall"/><div><H t="Architecture" s="Cantilevered slabs and travertine piers let the structure disappear. Nothing is decorative; everything carries weight or light."/></div></section>
<section className="sec"><H t="Interiors" s="Oak, plaster and stone under double-height ceilings."/><div className="row3">{(['living','kitchen','bedroom'] as const).map((k,i)=><Pic key={k} src={art(30+i,k)} alt={`${k} interior`} cls="tall par"/>)}</div></section>
<section id="experience" className="sec split"><div><H t="Living here" s="Mornings begin with light across the kitchen island. Evenings end on the terrace, the pool lit from below, the city a soft grid in the distance."/></div><Pic src={art(41,'terrace')} alt="Terrace at dusk"/></section>
<section className="sec"><H t="Amenities"/><ul className="grid4">{amen.map((a,i)=><li key={a} className="card"><Pic src={art(50+i,(['pool','bath','living','bedroom','kitchen','garden','terrace','exterior'] as const)[i])} alt={a}/><h3>{a}</h3></li>)}</ul></section>
<section className="sec"><H t="Architectural details"/><ul className="mosaic">{det.map(([n,k,s])=><li key={n}><Pic src={art(s*3,k)} alt={n}/><span>{n}</span></li>)}</ul></section>
<section className="sec split"><div><H t="Location" s="Nine minutes to Beverly Hills, twenty to Malibu, forty to LAX. Private road, gated, and quiet."/><ul className="facts"><li>Runyon Canyon trails · 6 min</li><li>Sunset Strip · 12 min</li><li>Pacific coast · 22 min</li></ul></div><div className="map" role="img" aria-label="Map of Los Angeles with Aurelia Estate marked">{Array.from({length:9}).map((_,i)=><i key={i} style={{left:i*12.5+'%'}}/>)}{Array.from({length:6}).map((_,i)=><b key={i} style={{top:i*18+'%'}}/>)}<span className="pin">Aurelia</span></div></section>
<section className="sec"><H t="Featured properties"/><ul className="grid3">{properties.slice(1,7).map(p=><li key={p.id}><Link href={`/properties/${p.slug}`} className="card"><Pic src={p.heroImage} alt={`${p.name} exterior`}/><h3>{p.name}</h3><p>{p.location} · {usd(p.price)}</p></Link></li>)}</ul></section>
<section className="sec"><H t="Clients"/>{testimonials.map((t,i)=><figure key={t.name} className={'quote '+(i%2?'rev':'')}><Pic src={art(70+i,'portrait')} alt={`Portrait of ${t.name}`} cls="portrait par"/><figcaption><p aria-label="5 out of 5 stars" className="stars">★★★★★</p><blockquote>“{t.text}”</blockquote><cite>{t.name}<br/><span>{t.role}</span></cite></figcaption></figure>)}</section>
<section className="cta"><Pic src={art(88,'exterior')} alt="Aurelia Estate at dusk" sizes="100vw"/><div><h2>Find your next address.</h2><Link className="pill" href="/properties">Explore the collection</Link></div></section></>}
